services:
  app:
    build:
      context: ../..
      dockerfile: deploy/Dockerfile.stage
    environment:
      SPRING_PROFILES_ACTIVE: stage
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: everygsm
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data: