spring:
  application:
    name: everygsm.server.v2
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    datagsm:
      openapi:
        api-key: ${DATAGSM_OPENAPI_KEY}
        sync-cron: "0 0 3 * * *"
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET}
      stack:
        auto: false

server:
  shutdown: graceful
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 60

oauth:
  datagsm:
    client-id: ${DATAGSM_CLIENT_ID}
    client-secret: ${DATAGSM_CLIENT_SECRET}
    redirect-uris: ${DATAGSM_REDIRECT_URIS:http://localhost:3000,http://localhost:3001}
