FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY build/libs/app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xms64m", "-Xmx280m", "-XX:MetaspaceSize=64m", "-XX:MaxMetaspaceSize=150m", "-XX:CompressedClassSpaceSize=32m", "-XX:+UseSerialGC", "-jar", "app.jar"]
