FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY build/libs/app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xms128m", "-Xmx400m", "-XX:MaxMetaspaceSize=100m", "-XX:+UseSerialGC", "-jar", "app.jar"]
