name: EveryGSM stage CD workflow

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: themoment/everygsm
          stage: main
          yaml: |
            name: everygsm-stage
            app: dockerfile
            options:
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: stage
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: AWS_ACCESS_KEY_ID
                  value: ${{ secrets.AWS_ACCESS_KEY_ID }}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                - name: AWS_S3_BUCKET
                  value: ${{ secrets.AWS_S3_BUCKET }}
                - name: DATAGSM_OPENAPI_KEY
                  value: ${{ secrets.DATAGSM_OPENAPI_KEY }}
                - name: DATAGSM_CLIENT_ID
                  value: ${{ secrets.DATAGSM_CLIENT_ID }}
                - name: DATAGSM_CLIENT_SECRET
                  value: ${{ secrets.DATAGSM_CLIENT_SECRET }}
                - name: DATAGSM_REDIRECT_URIS
                  value: ${{ secrets.DATAGSM_REDIRECT_URIS }}
                - name: DATAGSM_API_URL
                  value: ${{ secrets.DATAGSM_API_URL }}
              ports: 8080
              dockerfile: deploy/Dockerfile.stage
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}

      - name: CD Success Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0x4CAF50

      - name: CD Failure Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFF4C4C

      - name: CD Cancelled Notification
        uses: sarisia/actions-status-discord@v1
        if: cancelled()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFFC107
