name: EveryGSM stage CD workflow

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: themoment/everygsm
          stage: main
          yaml: |
            name: everygsm-stage
            app: dockerfile
            options:
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: stage
                - name: DB_HOST
                  secret: DB_HOST
                - name: DB_PORT
                  secret: DB_PORT
                - name: DB_USERNAME
                  secret: DB_USERNAME
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: JWT_SECRET_KEY
                  secret: JWT_SECRET_KEY
                - name: AWS_ACCESS_KEY_ID
                  secret: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  secret: AWS_SECRET_ACCESS_KEY
                - name: AWS_S3_BUCKET
                  secret: AWS_S3_BUCKET
              ports: 8080
              dockerfile: deploy/Dockerfile.stage
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
